[".local/share/nvim/site/pack/paqs/start/paq-nvim"]
    type = "archive"
    url = "https://github.com/savq/paq-nvim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/zsh/oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/zsh/oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/zsh/oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/tmux/plugins/tmux-df"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/tmux/plugins/tmux-cpu"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tmux-cpu/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/tmux/plugins/tmux-net-speed"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tmux-net-speed/archive/refs/heads/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/tmux/plugins/tmux-resurrect"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tmux-resurrect/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/tmux/plugins/vim-tmux-navigator"]
    type = "archive"
    url = "https://github.com/christoomey/vim-tmux-navigator/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/tmux/plugins/tmux-prefix-highlight"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tmux-prefix-highlight/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
