---

- hosts: localhost
  connection: local

  tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Ensure basic packages are present
      become: yes
      package:
        name:
          - curl
          - wget

    - name: Install chezmoi
      shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply Shishqa
