#!/bin/sh
############################################################################

[ -f "$BSPWM_CONFIG/desktops" ] && source "$BSPWM_CONFIG/desktops"

killall picom && picom &

nitrogen --restore &

~/.config/polybar/scripts/launch-polybar &

killall dunst && dunst &

killall batsignal && batsignal -b &

killall flameshot && flameshot &

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# [!!!] IMPORTANT FOR JetBrains APPS
# see https://github.com/baskerville/bspwm/issues/52
wmname LG3D

############################################################################
