#!/bin/sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

CONFIG=$HOME/.config/polybar/bars.ini

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --config=$CONFIG top &
#    MONITOR=$m polybar --reload --config=$CONFIG bottom &
  done
else
  polybar --config=$CONFIG top &
#  polybar --reload --config=$CONFIG bottom &
fi
